// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUk_g49rWWi29DHtzXeuJywP3cm9vtjB0',
    appId: '1:241329411586:web:564c2579e6511aaac4791b',
    messagingSenderId: '241329411586',
    projectId: 'comic-fest-app',
    authDomain: 'comic-fest-app.firebaseapp.com',
    storageBucket: 'comic-fest-app.firebasestorage.app',
    measurementId: 'G-5JZ025WN4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi44XkO4KPj9Guyg5EEpn9YAHoeiHrTEw',
    appId: '1:241329411586:android:a02b34fdb3988239c4791b',
    messagingSenderId: '241329411586',
    projectId: 'comic-fest-app',
    storageBucket: 'comic-fest-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkUSVxDXBxgDMH6uXwLmc19T0GbowoBxM',
    appId: '1:241329411586:ios:e2cd0d974aea9198c4791b',
    messagingSenderId: '241329411586',
    projectId: 'comic-fest-app',
    storageBucket: 'comic-fest-app.firebasestorage.app',
    androidClientId: '241329411586-vrm25dhekamqev8puhbk420hs8k9ld1o.apps.googleusercontent.com',
    iosClientId: '241329411586-ngotenvd30tr52j90oi83ts43k2lgrnn.apps.googleusercontent.com',
    iosBundleId: 'com.comicfest.app',
  );

}